#+ summary: Search for UniProt accessions based on various criteria
#+ description: Returns UniProt protein accessions filtered by organism, review status, subcellular location, molecular function, and sequence length
#+ endpoint: https://sparql.uniprot.org/sparql
#+ endpoint_in_url: False
#+ method: POST
#+ enumerate:
#+   - reviewed:
#+     - "true"
#+     - "false"
#+ pagination: 1000
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX taxon: <http://purl.uniprot.org/taxonomy/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX GO:<http://purl.obolibrary.org/obo/GO_>

SELECT DISTINCT ?protein
WHERE {
    ?protein a up:Protein .

    # Taxon filter (optional)
    OPTIONAL {
        BIND(IRI(CONCAT("http://purl.uniprot.org/taxonomy/", STR(?__taxon_integer))) AS ?taxonIRI)
        ?protein up:organism ?taxonIRI .
    }

    # Reviewed filter (optional)
    OPTIONAL {
        ?protein up:reviewed ?__reviewed_xsd_boolean .
    }

    # Subcellular location UniProt (optional)
    OPTIONAL {
        ?protein up:annotation ?subcellAnnotation .
        ?subcellAnnotation up:locatedIn/up:cellularComponent ?cellcmpt .
        ?cellcmpt skos:prefLabel ?__subCellularLocationUniprot .
    }

    # Subcellular location GO (optional)
    OPTIONAL {
        ?protein up:classifiedWith|(up:classifiedWith/rdfs:subClassOf+) ?__subCellularLocationGo .
    }

    # Molecular function GO (optional)
    OPTIONAL {
        ?protein up:classifiedWith|(up:classifiedWith/rdfs:subClassOf+) ?__molecularFunctionGo .
    }

    # Sequence length filter (optional)
    FILTER(BOUND(?__minimumSequenceLength) || BOUND(?__maximumSequenceLength))
    OPTIONAL {
        ?protein up:sequence ?isoform .
        ?isoform a up:Simple_Sequence .
        BIND (IRI(STRBEFORE(REPLACE(
            STR(?isoform), "http://purl.uniprot.org/isoforms/", "http://purl.uniprot.org/uniprot/"
        ), "-")) AS ?ac_of_isoform)
        FILTER (?protein = ?ac_of_isoform)
        ?isoform rdf:value ?sequence .
        BIND (STRLEN(?sequence) AS ?seq_length)
        FILTER(
            (!BOUND(?__minimumSequenceLength) || ?seq_length >= ?__minimumSequenceLength) &&
            (!BOUND(?__maximumSequenceLength) || ?seq_length <= ?__maximumSequenceLength)
        )
    }
}
