"""Generate the shared cache configuration template for Protein Quest."""

import inspect
from pathlib import Path
from typing import Annotated, Any, get_args, get_origin, get_type_hints

from cyclopts.docs.base import iterate_commands

from protein_quest.cli import app
from protein_quest.cli.common import CacheParameter


def _annotation_contains_cache_parameter(annotation: Any) -> bool:
    """Return True when an annotation includes CacheParameter."""
    if annotation is CacheParameter:
        return True

    origin = get_origin(annotation)
    if origin is None:
        return False

    if origin is Annotated:
        return any(_annotation_contains_cache_parameter(arg) for arg in get_args(annotation))

    return any(_annotation_contains_cache_parameter(arg) for arg in get_args(annotation))


def _command_uses_cache_parameter(command: Any) -> bool:
    """Return True when a command has a cache parameter typed with CacheParameter."""
    if not callable(command):
        return False

    signature = inspect.signature(command)
    cache_parameter = signature.parameters.get("cache")
    if cache_parameter is None:
        return False

    hints = get_type_hints(command, include_extras=True)
    annotation = hints.get("cache", cache_parameter.annotation)
    return _annotation_contains_cache_parameter(annotation)


def _iter_cache_command_paths(current_app: Any, prefix: tuple[str, ...] = ()):
    """Yield command paths for commands that accept CacheParameter."""
    for name, subapp in iterate_commands(current_app, include_hidden=False):
        path = (*prefix, name)

        if subapp.default_command and _command_uses_cache_parameter(subapp.default_command):
            yield path

        if subapp._commands:
            yield from _iter_cache_command_paths(subapp, path)


def build_shared_config_template() -> str:
    """Build TOML content for shared cache settings across cache-enabled commands."""
    sections = [".".join(path) for path in _iter_cache_command_paths(app)]

    if not sections:
        msg = "No cache-enabled commands were found while generating docs/example-shared-config.toml."
        raise RuntimeError(msg)

    lines = [
        "# This file was generated by `uv run docs/generated-example-shared-config.py`.",
        "# It is intended to be used as a template for a shared configuration file for Protein Quest.",
        "# If cache parameters change or commands in src/protein_quest/cli/ change, this file should be updated.",
        "",
    ]

    for section in sections:
        lines.append(f"[{section}]")
        lines.append('cache_dir = "/shared/protein-quest-cache"')
        lines.append('copy_method = "symlink"')
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    """Generate docs/example-shared-config.toml."""
    output_file = Path(__file__).with_name("example-shared-config.toml")
    content = build_shared_config_template()
    output_file.write_text(content, encoding="utf-8")
    print(f"Wrote {output_file}.")  # noqa: T201


if __name__ == "__main__":
    main()
